Update

diff --git a/misc/co b/misc/co
--- a/misc/co
+++ b/misc/co
@@ -1,28 +1,12 @@
 #!/bin/sh
 
+if ! [ -f "/etc/co" ]; then
+	echo 'File /etc/co with completions not found' >&2
+	sleep 2
+	exit 1
+fi
 args="$@"
 tmp="$(mktemp)"
-tmux popup -E "fzf $FZF_DEFAULT_OPTS -1 -q \"$args\" > \"$tmp\" <<EOM
-int main(int argc, char **argv) 
-public class Main 
-public static void main(String[] args) 
-Scanner sc = new Scanner(System.in);
-for line in io.lines() do
-for(int i = 0; i < ; i++)
-import java.util.*;
-import java.io.*;
-import java.util.concurrent.*;
-#include <stdio.h>
-#include <stdlib.h>
-#include <string.h>
-#include <stdint.h>
-#include <stddef.h>
-#pragma once
-System.out.println("");
-printf("", );
-fprintf(stderr, "", );
-#!/bin/sh
-#!/usr/bin/env lua
-EOM"
+tmux popup -E "fzf $FZF_DEFAULT_OPTS -1 -q \"$args\" > \"$tmp\" </etc/co"
 cat "$tmp"
 rm "$tmp"
